// Word Quest 單字庫：2A Final Exam Review Word List 2026
// 遊戲格式：{ id, en, kk, zh }
// id 不可重複；en 是英文；kk 是音標；zh 是中文選項文字。

window.WORD_QUEST_WORD_BANK = [
  { id: "blanket", en: "blanket", kk: "[ˋblæŋkɪt]", zh: "毯子" },
  { id: "blend", en: "blend", kk: "[blɛnd]", zh: "混合" },
  { id: "blink", en: "blink", kk: "[blɪŋk]", zh: "眨眼" },
  { id: "block", en: "block", kk: "[blɑk]", zh: "積木；街區；阻擋" },
  { id: "burned", en: "burned", kk: "[bɝnd]", zh: "燒傷；燒焦" },
  { id: "city", en: "city", kk: "[ˋsɪtɪ]", zh: "城市" },
  { id: "flute", en: "flute", kk: "[flut]", zh: "長笛" },
  { id: "gate", en: "gate", kk: "[get]", zh: "大門" },
  { id: "glad", en: "glad", kk: "[glæd]", zh: "高興的" },
  { id: "grand", en: "grand", kk: "[grænd]", zh: "宏偉的；大的" },
  { id: "grave", en: "grave", kk: "[grev]", zh: "墳墓" },
  { id: "grow", en: "grow", kk: "[gro]", zh: "成長；種植" },
  { id: "home", en: "home", kk: "[hom]", zh: "家" },
  { id: "lunch", en: "lunch", kk: "[lʌntʃ]", zh: "午餐" },
  { id: "mend", en: "mend", kk: "[mɛnd]", zh: "修補" },
  { id: "mess", en: "mess", kk: "[mɛs]", zh: "髒亂；混亂" },
  { id: "must", en: "must", kk: "[mʌst]", zh: "必須" },
  { id: "prune", en: "prune", kk: "[prun]", zh: "西梅乾；李子乾" },
  { id: "rush", en: "rush", kk: "[rʌʃ]", zh: "衝；匆忙" },
  { id: "send", en: "send", kk: "[sɛnd]", zh: "寄送；傳送" },
  { id: "skip", en: "skip", kk: "[skɪp]", zh: "跳過；蹦跳" },
  { id: "smile", en: "smile", kk: "[smaɪl]", zh: "微笑" },
  { id: "smoke", en: "smoke", kk: "[smok]", zh: "冒煙；吸菸" },
  { id: "stamp", en: "stamp", kk: "[stæmp]", zh: "郵票；印章" },
  { id: "sting", en: "sting", kk: "[stɪŋ]", zh: "刺；螫" },
  { id: "stove", en: "stove", kk: "[stov]", zh: "爐子" },
  { id: "stuck", en: "stuck", kk: "[stʌk]", zh: "卡住；困住" },
  { id: "test", en: "test", kk: "[tɛst]", zh: "測驗" },
  { id: "train", en: "train", kk: "[tren]", zh: "訓練" },
  { id: "trim", en: "trim", kk: "[trɪm]", zh: "修剪" },
  { id: "at_last", en: "at last", kk: "[æt læst]", zh: "最後；終於" },
  { id: "close_adj", en: "close", kk: "[klos]", zh: "親近的；靠近的" },
  { id: "delighted", en: "delighted", kk: "[dɪˋlaɪtɪd]", zh: "高興的；欣喜的" },
  { id: "evergreen", en: "evergreen", kk: "[ˋɛvɚˌgrin]", zh: "常綠的" },
  { id: "first", en: "first", kk: "[fɝst]", zh: "第一的" },
  { id: "float", en: "float", kk: "[flot]", zh: "漂浮" },
  { id: "growled", en: "growled", kk: "[graʊld]", zh: "低吼；咆哮" },
  { id: "idea", en: "idea", kk: "[aɪˋdiə]", zh: "想法；主意" },
  { id: "plan", en: "plan", kk: "[plæn]", zh: "計畫；計畫做" },
  { id: "kitchen", en: "kitchen", kk: "[ˋkɪtʃən]", zh: "廚房" },
  { id: "land", en: "land", kk: "[lænd]", zh: "著陸；降落" },
  { id: "learn", en: "learn", kk: "[lɝn]", zh: "學習" },
  { id: "lesson", en: "lesson", kk: "[ˋlɛsən]", zh: "課；課程" },
  { id: "proud_of", en: "proud of", kk: "[praʊd ʌv]", zh: "以……為榮" },
  { id: "sniff", en: "sniff", kk: "[snɪf]", zh: "聞一聞；嗅" },
  { id: "stream", en: "stream", kk: "[strim]", zh: "小溪；溪流" },
  { id: "sweep", en: "sweep", kk: "[swip]", zh: "打掃；掃" },
  { id: "weed", en: "weed", kk: "[wid]", zh: "雜草" },
  { id: "wonderful", en: "wonderful", kk: "[ˋwʌndɚfəl]", zh: "很棒的；美妙的" },
  { id: "muddy", en: "muddy", kk: "[ˋmʌdɪ]", zh: "泥巴的；泥濘的" },
  { id: "important", en: "important", kk: "[ɪmˋpɔrtṇt]", zh: "重要的" },
  { id: "belong", en: "belong", kk: "[bɪˋlɔŋ]", zh: "屬於" },
  { id: "shook", en: "shook", kk: "[ʃʊk]", zh: "搖動；震動" },
  { id: "understand", en: "understand", kk: "[ˌʌndɚˋstænd]", zh: "了解；明白" },
  { id: "alone", en: "alone", kk: "[əˋlon]", zh: "獨自；單獨" },
  { id: "cost", en: "cost", kk: "[kɔst]", zh: "花費" },
  { id: "spend", en: "spend", kk: "[spɛnd]", zh: "花費；度過" }
];
